### PR TITLE
Add, search, pagination and sort capabilities in api through search endpoint.

### PR DESCRIPTION
**Pull request by mishraomp**
---

Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-quickstart-typescript-1088-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-quickstart-typescript-1088-frontend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-quickstart-typescript/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by mishraomp** [comment]
looks like sonar is not working for some reason, I have added the UTs but it is still failing and showing 0% coverage

**Review by DerekRoberts — APPROVED** [review]
Wow! You move fast. :D

**Comment by DerekRoberts** [comment]
> looks like sonar is not working for some reason, I have added the UTs but it is still failing and showing 0% coverage

Is it included in the default run? We can check the coverage reports.

**Comment by mishraomp** [comment]
@DerekRoberts can we disable sonar, otherwise I wont be able to merge as it wont allow

**Comment by mishraomp** [comment]
> > looks like sonar is not working for some reason, I have added the UTs but it is still failing and showing 0% coverage
> 
> Is it included in the default run? We can check the coverage reports.

yes it is.

**Comment by mishraomp** [comment]
@DerekRoberts the tests are inside the src folder and named as *.spec.ts
https://github.com/bcgov/nr-quickstart-typescript/blob/main/backend/package.json#L96

**Comment by DerekRoberts** [comment]
> > > looks like sonar is not working for some reason, I have added the UTs but it is still failing and showing 0% coverage
> > 
> > 
> > Is it included in the default run? We can check the coverage reports.
> 
> yes it is.

Coverage reports aren't turning up wonderfully for the new code.  Let's get this figured out next week.  :)
```
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------|---------|----------|---------|---------|-------------------     
 src/users            |   49.33 |    21.42 |   43.75 |   47.82 |                   
  users.controller.ts |   78.26 |      100 |   16.66 |   76.19 | 23,28,46,51,56    
  users.module.ts     |       0 |      100 |     100 |       0 | 1-12              
  users.service.ts    |   43.18 |        0 |      60 |   40.47 | 51-102  
```

**Comment by DerekRoberts** [comment]
> @DerekRoberts the tests are inside the src folder and named as *.spec.ts https://github.com/bcgov/nr-quickstart-typescript/blob/main/backend/package.json#L96

Oh!  Okay, let's see about pointing SonarCloud to them.  Won't take long.

**Comment by mishraomp** [comment]
@DerekRoberts tried my best lets see whats missing from sonar point of view
```
----------------------|---------|----------|---------|---------|-------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------|---------|----------|---------|---------|-------------------
All files             |   72.18 |    54.54 |   95.23 |   72.26 |                   
 src                  |   34.21 |        0 |      75 |   28.12 |                   
  app.controller.ts   |     100 |      100 |     100 |     100 |                   
  app.module.ts       |       0 |        0 |     100 |       0 | 1-38              
  app.service.ts      |     100 |      100 |     100 |     100 |                   
  main.ts             |       0 |      100 |       0 |       0 | 1-19              
 src/users            |      84 |    85.71 |     100 |    85.5 |                   
  users.controller.ts |     100 |      100 |     100 |     100 |                   
  users.module.ts     |       0 |      100 |     100 |       0 | 1-12              
  users.service.ts    |    90.9 |    81.81 |     100 |   90.47 | 80,86,96,100      
 src/users/dto        |     100 |      100 |     100 |     100 |                   
  create-user.dto.ts  |     100 |      100 |     100 |     100 |                   
  update-user.dto.ts  |     100 |      100 |     100 |     100 |                   
  user.dto.ts         |     100 |      100 |     100 |     100 |                   
 src/users/entities   |     100 |      100 |     100 |     100 |                   
  users.entity.ts     |     100 |      100 |     100 |     100 |                   
----------------------|---------|----------|---------|---------|-------------------
```

**Comment by mishraomp** [comment]
Success @DerekRoberts  , yay

**Pull request merged**
